[logging]
# Global logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "DEBUG"

# Console logging settings
console_level = "DEBUG"
console_format = "%(log_color)s%(levelname)-8s%(reset)s | %(asctime)s | %(name)s | %(message)s"

# File logging settings
file_logging = true
file_level = "DEBUG"
file_format = "%(levelname)-8s | %(asctime)s | %(name)s | %(message)s"
date_format = "%Y-%m-%d %H:%M:%S"
log_dir = "logs"
log_file = "dev.log"
max_file_size = 5242880  # 5MB
backup_count = 5

# Component-specific log levels
# [logging.components]
# commands = "INFO"
# events = "DEBUG" 
# http = "WARNING"
# voice = "INFO"
# database = "DEBUG"
# reaction = "INFO"
# moderation = "DEBUG"
# automod = "DEBUG"